import { afterEach, describe, expect, it, vi } from 'vitest';
import { loadMarket } from '../server/market';
import { REGISTRY } from '../shared/types';
const tokens = { code: 0, data: { tokenList: (['USDT', 'USDD'] as const).map(asset => ({ address: REGISTRY[asset].address, underlyingAddress: REGISTRY[asset].underlyingAddress, underlyingSymbol: asset, underlyingDecimal: REGISTRY[asset].decimals, supplyRate: asset === 'USDT' ? '0.02' : '0.00001', cash: '1000000' })) } };
function mock(updates: { corrupt?: boolean; missingDocs?: boolean; badCode?: boolean; rate?: string; missingBonus?: boolean } = {}) { vi.stubGlobal('fetch', vi.fn(async (url: string) => { if (url.includes('usdd.io')) { if (updates.missingDocs) throw new Error('unavailable'); return new Response('USDD official description. '.repeat(30)); } if (url.includes('jtoken')) { const body = structuredClone(tokens); if (updates.corrupt) body.data.tokenList[1].underlyingAddress = REGISTRY.USDT.underlyingAddress; if (updates.badCode) body.code = 1; if (updates.rate) body.data.tokenList[0].supplyRate = updates.rate; return Response.json(body); } if (url.includes('/mining/apy')) { if (updates.missingBonus) throw new Error('unavailable'); return Response.json({ code: 0, data: { [REGISTRY.USDD.address]: { USDD: '0.04' } } }); } return Response.json({ code: 0, data: { [REGISTRY.USDD.address]: { USDD: { currEndTime: '2026-10-03 20:00' } } } }); })); }
afterEach(() => vi.unstubAllGlobals());
describe('official read-only market adapter', () => {
  it('normalizes fractional APR, fixed token identity, and separate bonus', async () => { mock(); const snapshot = await loadMarket(); expect(snapshot.mode).toBe('live'); expect(snapshot.markets.USDT.baseRate).toBe(0.02); expect(snapshot.markets.USDD.incentiveRate).toBe(0.04); expect(snapshot.sources).toHaveLength(3); expect(snapshot.sources.every(s => s.status === 'live')).toBe(true); expect(snapshot.phaseEnd).toBe('2026-10-03 20:00'); expect(snapshot.incentiveDaysVerified).toBe(0); });
  it.each([{ corrupt: true }, { badCode: true }, { rate: 'NaN' }, { rate: '-0.1' }, { missingBonus: true }])('fails to explicit demo data for unavailable/untrusted core rates %j', async condition => { mock(condition); const snapshot = await loadMarket(); expect(snapshot.mode).toBe('demo'); expect(snapshot.sources.every(s => s.status === 'unavailable')).toBe(true); expect(snapshot.warnings.join('')).toContain('演示'); });
  it('keeps USDD document failure visibly separate from live rate API', async () => { mock({ missingDocs: true }); const snapshot = await loadMarket(); expect(snapshot.mode).toBe('live'); expect(snapshot.sources.find(s => s.url.includes('usdd.io'))?.status).toBe('unavailable'); expect(snapshot.warnings.join('')).toContain('未读通'); });
  it('handles network failure without inventing live evidence', async () => { vi.stubGlobal('fetch', vi.fn().mockRejectedValue(new Error('temporary secret diagnostic'))); const snapshot = await loadMarket(); expect(snapshot.mode).toBe('demo'); expect(JSON.stringify(snapshot)).not.toContain('secret'); });
});
